version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:45"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Parser version should match Ruby version
      - dependency-name: "parser"
      - dependency-name: "mini_racer"
      # Byebug 12.0.0 requires Ruby 3.1+
      - dependency-name: "byebug"
      - dependency-name: "faker"
        update-types:
          - version-update:semver-major
