version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:45"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      # parser shall be same version as Ruby
      - dependency-name: "parser"
      - dependency-name: "mini_racer"
      - dependency-name: "faker"
        update-types:
          - version-update:semver-major
