# [START cloudrun_rails_cloudbuild]
steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build -f Dockerfile.run \
          --build-arg SECRET_KEY_BASE=$$RAILS_KEY \
          -t gcr.io/${PROJECT_ID}/${_SERVICE_NAME} \
          --cache-from gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest \
          .
    secretEnv: ["RAILS_KEY"]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image gcr.io/${PROJECT_ID}/${_SERVICE_NAME} \
          --update-env-vars=RAILS_MASTER_KEY=$$RAILS_KEY \
          --update-env-vars=SECRET_KEY_BASE=$$RAILS_KEY \
          --update-env-vars=DB_HOST=$$DB_HOST \
          --update-env-vars=DB_PORT=$$DB_PORT \
          --update-env-vars=DB_NAME=$$DB_NAME \
          --update-env-vars=DB_USER=$$DB_USER \
          --update-env-vars=DB_PASS=$$DB_PASS \
          --update-env-vars=RAILS_SERVE_STATIC_FILES=true \
          --update-env-vars=GOOGLE_PROJECT_ID=${PROJECT_ID} \
          --update-env-vars=GOOGLE_CLOUD_BUCKET_NAME=$$BUCKET_NAME \
          --update-env-vars=GOOGLE_CLOUD_STORAGE_ISSUER=$$STORAGE_ISSUER \
          --update-env-vars=GOOGLE_CLOUD_STORAGE_PRIVATE_KEY=${_STORAGE_PRIVATE_KEY} \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 1 \
          --min-instances 0 \
          --concurrency 80 \
          --timeout 300s
    secretEnv:
      - "RAILS_KEY"
      - "DB_HOST"
      - "DB_PORT"
      - "DB_NAME"
      - "DB_USER"
      - "DB_PASS"
      - "BUCKET_NAME"
      - "STORAGE_ISSUER"

substitutions:
  _SERVICE_NAME: rails-cloud-run-chat
  _SECRET_NAME: RAILS_KEY
  _STORAGE_PRIVATE_KEY: ""

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/${_SECRET_NAME}/versions/latest
      env: RAILS_KEY
    - versionName: projects/${PROJECT_ID}/secrets/CHAT_DB_HOST/versions/latest
      env: DB_HOST
    - versionName: projects/${PROJECT_ID}/secrets/CHAT_DB_PORT/versions/latest
      env: DB_PORT
    - versionName: projects/${PROJECT_ID}/secrets/CHAT_DB_NAME/versions/latest
      env: DB_NAME
    - versionName: projects/${PROJECT_ID}/secrets/CHAT_DB_USER/versions/latest
      env: DB_USER
    - versionName: projects/${PROJECT_ID}/secrets/CHAT_DB_PASS/versions/latest
      env: DB_PASS
    - versionName: projects/${PROJECT_ID}/secrets/CHAT_BUCKET_NAME/versions/latest
      env: BUCKET_NAME
    - versionName: projects/${PROJECT_ID}/secrets/GOOGLE_CLOUD_STORAGE_ISSUER/versions/latest
      env: STORAGE_ISSUER

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"

options:
  logging: CLOUD_LOGGING_ONLY
# [END cloudrun_rails_cloudbuild]
