version: '3'
services:
  test_db:
    image: mysql:5.7.41
    platform: linux/x86_64
    volumes:
      - test_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    expose:
      - "3307"
    networks:
      - chat-space-network

  test_web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/chat-space
      - test_bundle:/usr/local/bundle
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: test
      DB_HOST: test_db
      DB_PORT: 3306
      DB_NAME: chat-space_test
      DB_USER: root
      DB_PASS: root
      SECRET_KEY_BASE_DUMMY: dummy
    depends_on:
      - test_db

    networks:
      - chat-space-network

volumes:
  test_db_data:
  test_bundle:

networks:
  chat-space-network:
